### ISSUE TITLE
Use AI21 LLM as a fallback does not work

### ISSUE THREAD

**Issue by JadyLiu** [aws-samples/qnabot-on-aws-plugin-samples#8]
Hi Team,

I follow up the instruction to configure my QnA bot 5.4.2 to fallback with LLM, the performance is not reliable, please find the screenshot of my bot and advise how to improve it. Thanks!
Also, I looked into CloudWatch of my QNA-LAMBDAHOOK, it is not triggered at all. 
<img width="914" alt="Screenshot 2023-10-01 at 12 45 33 AM" src="https://github.com/aws-samples/qnabot-on-aws-plugin-samples/assets/17633801/8c17e627-8789-4d0c-affd-ae63cf46245a">

**Comment by rstrahan** [comment]
Hi @JadyLiu - Can you disable Kendra by removing the Kendra indexId from `ALT_SEARCH_KENDRA_INDEXES` in Contrent Designer Settings, and try again?

The issue you are seeing is that Fallback / no_hits isn't getting invoked because instead Kendra RetrieveAPI is returning some resulting text passages from your index (probably not relevant ones, but there is sadly no relevance threshold), and the LLM RAG feature is asking the LLM to generate an answer from those results, which it is doing... So no_hits never gets triggered.  

Do you need LLM fallback in addition to RAG? You could try to achieve that by experimenting with changes to the `LLM_QN_PROMPT_TEMPLATE` - and possibly also the `LLM_QA_NO_HITS_REGEX` which lets you invoke no_hits based on a pattern match in the LLM RAG response.

Anyway, start by just disabling Kendra (my first point above) and see if the Fallback works.

**Comment by JadyLiu** [comment]
Hi @rstrahan, you are correct. The fallback lambda is triggered when I remove the KENDRA INDEX. I follow your instruction to use NO_HITS_REGEX with a pattern from PROMPT_TEMPLATE to invoke no_hit from RAG response. It worked. While I would think it is worth having a new feature to fallback with relevance threshold to make it more controllable.

Thank you for the help!
Jady
